add unsupported psi type as default value
Optable/match pull request #55
Opened 2021-11-22 14:51 UTC by juanli16

Add default Unsupported PSI type

2021-11-22 15:20 UTC, xcapaldi approved these changes

2021-11-22 15:36 UTC, ratelle requested changes

2021-11-22 15:36 UTC, ratelle commented on pkg/psi/psi.go
> +	ProtocolUnsupported Protocol = Unsupported
Use the Protocol type in the const, that way you don't need this var block.

2021-11-22 15:36 UTC, ratelle commented on pkg/psi/psi.go
> +	ProtocolUnsupported Protocol = Unsupported
https://yourbasic.org/golang/iota/

2021-12-06 21:03 UTC, ratelle approved these changes

2021-12-06 21:04 UTC, merged